version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 351138146362.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - cat Dockerfile
      - echo build Docker image on `date`
      - docker build --build-arg NODE_ENV=$NODE_ENV --tag catalog_app:$IMAGE_TAG .
      - docker tag catalog_app:$IMAGE_TAG 351138146362.dkr.ecr.ap-south-1.amazonaws.com/catalog_app:$IMAGE_TAG
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 351138146362.dkr.ecr.ap-south-1.amazonaws.com/catalog_app:$IMAGE_TAG
